on:
  push:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install tensorflow-cpu
    - run: python -c 'exec(open("README.md").read().split("```")[1][6:])'
